INSERT INTO public.welfare_technologies (
    title, description, category, tags, url, image_url,
    manufacturer, country_availability, notes, published, created_by
  ) VALUES
(
      'Hepro',
      'Norsk leverandør av velferdsteknologi til kommuner, helseforetak og institusjoner — med vekt på større selvstendighet for eldre og avlastning for helsepersonell. Tilbyr mobile og stasjonære digitale trygghetsalarmer, pasientvarsling, lokalisering og digitalt tilsyn, samlet i skyplattformen Hepro Respons. Plattformen brukes av over 170 norske kommuner og kan integrere utstyr fra flere leverandører i ett felles grensesnitt.',
      'Trygghet i hjemmet',
      ARRAY['trygghetsalarm', 'plattform', 'digitalt tilsyn', 'pasientvarsling']::text[],
      'https://hepro.no/forside/velferdsteknologi/',
      NULL,
      'Hepro AS',
      ARRAY['Norge']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Tellu',
      'Norsk teknologileverandør som tilbyr høyteknologiske velferdsløsninger samlet i ett komplett økosystem. TelluCare-plattformen knytter trygghetsalarmer, digitalt tilsyn, digital hjemmeoppfølging, medisinstøtte og responssenter sammen i ett brukergrensesnitt — for hjemmeboende, sykehjem og institusjoner. Over 100 norske kommuner bruker løsningene, og plattformen er bygget for integrasjon med nasjonale systemer som VKP og elektronisk pasientjournal.',
      'Tjenester rundt hjemmet',
      ARRAY['plattform', 'økosystem', 'trygghetsalarm', 'digitalt tilsyn', 'responssenter']::text[],
      'https://www.tellu.no/',
      NULL,
      'Tellu AS',
      ARRAY['Norge']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'MiniFinder',
      'GPS-baserte trygghetsløsninger i form av smartklokker og bærbare alarmer, blant annet MiniFinder Watch og MiniFinder Nano. Enhetene har innebygd SOS-knapp, sanntidsposisjonering via GPS og mobilnett, fallalarm og toveis tale — uten at brukeren trenger egen telefon. Leveres til kommuner, hjemmetjenester og private brukere, og administreres via appen MiniFinder Live.',
      'Trygghet i hjemmet',
      ARRAY['GPS', 'trygghetsalarm', 'fallalarm', 'klokke', 'mobil alarm']::text[],
      'https://minifinder.com/no/losninger/omsorg/trygghetsalarm/',
      NULL,
      'MiniFinder AB',
      ARRAY['Norge', 'Sverige']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Zembro',
      'Bærbare trygghetsalarmer for seniorer — som klokke, armbånd eller hengesmykke — med innebygd SIM-kort, GPS-sporing og toveis tale. Ved nødtrykk varsles forhåndsvalgte kontakter eller en alarmsentral, og pårørende kan følge med via app. Tilbys i flere europeiske land; i Norge finnes lignende GPS-baserte trygghetsløsninger fra andre leverandører, men Zembro er et eksempel på denne typen «wearable»-alarm uten behov for egen mobiltelefon.',
      'Trygghet i hjemmet',
      ARRAY['trygghetsalarm', 'GPS', 'armbånd', 'fallalarm', 'bærbart']::text[],
      'https://www.zembro.com/',
      NULL,
      'Zembro (UEST-NV)',
      ARRAY['Europa']::text[],
      'Relevant som eksempel på personlig alarmteknologi — nyttig å sammenligne med norske alternativer som Stella Care og kommunale GPS-løsninger.',
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Doro',
      'Mobiltelefoner utviklet for seniorer og andre som trenger enkel, tydelig kommunikasjon — fra enkle knappetelefoner til smarttelefoner i Aurora-serien. Alle modeller har innebygd Doro Secure-knapp: ett trykk sender alarm med GPS-posisjon til forhåndsvalgte kontakter, etterfulgt av automatisk oppringing. Kan kombineres med Doro 3500, en separat Bluetooth-alarmutløser for håndledd eller hals.',
      'Kontakt og kommunikasjon',
      ARRAY['mobiltelefon', 'trygghetsknapp', 'senior', 'enkel telefon']::text[],
      'https://www.doro.com/nb-no/trygghetsknapp/',
      NULL,
      'Doro AB',
      ARRAY['Norge', 'Sverige', 'Europa']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Sensio',
      'Norsk leverandør og en av Nordens ledende aktører innen velferdsteknologi, med fokus på trygghetssensorer, AI og en samlet plattform for eldreomsorg. Sensio 365 samler alarmer, sensorer og tjenester i ett grensesnitt, mens RoomMate er en passiv multisensor som oppdager fall og muliggjør anonymisert digitalt tilsyn uten at brukeren bærer utstyr. Tilbyr også Safemate trygghetsalarmer, lokaliseringstjenester og digitalt tilsyn — brukt i hjemmetjeneste, omsorgsboliger og sykehjem, deriblant avtale med Oslo kommune fra 2025.',
      'Trygghet i hjemmet',
      ARRAY['plattform', 'RoomMate', 'digitalt tilsyn', 'trygghetsalarm', 'AI', 'sensor']::text[],
      'https://www.sensio.com/no/produkter/sensio-365',
      NULL,
      'Sensio AS',
      ARRAY['Norge', 'Norden']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Suvanto Care',
      'Finsk innovasjon som gir kontinuerlig situasjonsinformasjon til pårørende og omsorgspersonell om en person som bor alene hjemme. Trådløse sensorer i boligen lærer seg beboerens rutiner og døgnrytme, og Suvanto Care-appen varsler ved avvik — for eksempel uvanlig søvn, manglende aktivitet eller at noe skjer utenfor det normale mønsteret. Tjenesten inkluderer også fjernmåling av helseverdier, videokommunikasjon og digital dagbok for kommunikasjon mellom pleiere og familie.',
      'Trygghet i hjemmet',
      ARRAY['app', 'sensorer', 'fjernoppfølging', 'avviksvarsling', 'hjemmeboende']::text[],
      'https://www.suvantocare.fi/en/front-page/',
      NULL,
      'Suvanto Care Oy',
      ARRAY['Finland', 'Norden']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Tunstall',
      'I over 65 år har Tunstall vært banebrytende med teknologi for helse- og omsorgssektoren. Løsningene muliggjør trygg og selvstendig livsstil for eldre og kronisk syke — gjennom digitale trygghetsalarmer (Lifeline Digital), GPS-klokker, bevegelsessensorer, komfyrvakter og elektroniske låser. Mer enn fem millioner mennesker bruker løsningene daglig globalt. I Norge leverer Tunstall integrerte systemer til hjemmetjeneste, omsorgsboliger og sykehjem.',
      'Trygghet i hjemmet',
      ARRAY['trygghetsalarm', 'GPS', 'sensorer', 'demens', 'pasientvarsling']::text[],
      'https://www.tunstall.no/',
      NULL,
      'Tunstall Norge AS',
      ARRAY['Norge', 'globalt']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Stella Care',
      'GPS-enheter utviklet spesifikt for personer med demens — for å finne de som har gått seg bort og skape trygghet for både kommuner og pårørende. Løsningen består av en bærbar GPS-enhet (flere modeller som klokke eller brikke), en sporingsapp og et administrasjonssystem for kommunalt personale. Brukes i dag av over 60 norske kommuner, med sanntidssporing, geofence-varsler og døgnåpen support.',
      'Trygghet i hjemmet',
      ARRAY['GPS', 'demens', 'lokalisering', 'geofence', 'klokke']::text[],
      'https://stellacare.dk/no/',
      NULL,
      'Stella Care ApS',
      ARRAY['Norge', 'Danmark', 'Skandinavia']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Wear&Care',
      'Dansk sensorteknologi for inkontinenspleie — en liten sensor festes på utsiden av alle typer bleer og varsler pleiepersonell via app når det er vannlating eller bleen er full. Løsningen muliggjør behovsbaserte blebytter i stedet for faste runder, reduserer unødvendige forstyrrelser og gir innsikt i vannlatingsmønster som kan avdekke helseendringer. Fungerer uten lokalt Wi-Fi og passer til sykehjem, omsorgsboliger og hjemmepleie.',
      'Trygghet i hjemmet',
      ARRAY['inkontinens', 'sensor', 'ble', 'helseovervåking']::text[],
      'https://wearandcare.com/da/hjem/',
      NULL,
      'Wear&Care Technologies',
      ARRAY['Danmark', 'Norden']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Securitas Technology',
      'Global leverandør og integrator av sikkerhets- og velferdsteknologi til helse- og omsorgssektoren. Tilbyr pasientvarslingssystemer, wander management (sporing av personer med demens), sanntids lokalisering (RTLS), spedbarnssikkerhet og integrerte sikkerhetsøkosystemer for sykehjem og omsorgsinstitusjoner. I Norge leverer de blant annet pasientvarsling til Trondheim kommunes nye Høyset helse- og velferdssenter, integrert med Helseplattformen.',
      'Trygghet i hjemmet',
      ARRAY['pasientvarsling', 'RTLS', 'wander management', 'integrator']::text[],
      'https://www.securitastechnology.com/no/bransjer/helsesektoren',
      NULL,
      'Securitas Technology',
      ARRAY['Norge', 'globalt']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Vivago',
      'Finsk selskap som tilbyr smarte trygghets- og velværeløsninger for forebyggende omsorg. Løsningen kombinerer intelligent pasientkall med sanntidsovervåking av søvn, aktivitet og døgnrytme — med automatiske alarmer ved plutselige endringer i tilstand eller hvis brukeren ikke klarer å tilkalle hjelp selv. Skalerer fra hjemmeboende til sykehjem og sykehus, og distribueres i Norge via Atea. Over 100 000 brukere daglig i Europa.',
      'Trygghet i hjemmet',
      ARRAY['velvære', 'søvn', 'aktivitet', 'pasientvarsel', 'forebygging', 'klokke']::text[],
      'https://vivago.com/en/about-us',
      NULL,
      'Vivago Oy',
      ARRAY['Norge', 'Finland', 'Europa']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Sensorem',
      'Privat trygghetsalarm i form av GPS-klokke med innebygd SIM-kort, SOS-knapp og toveis tale via høyttalertelefon. Ved alarm varsles pårørende med GPS-posisjon via app og SMS, og dersom ingen svarer, kobles anropet til Sensorems døgnåpne alarmsentral. Fungerer overalt med mobildekning — også utendørs — og krever ikke tilknytning til kommunal hjemmetjeneste. Ingen bindingstid; populært alternativ for pårørende som ønsker trygghet utenfor det kommunale systemet.',
      'Trygghet i hjemmet',
      ARRAY['trygghetsalarm', 'GPS', 'klokke', 'privat', 'pårørende']::text[],
      'https://www.sensorem.com/no/',
      NULL,
      'Sensorem AB',
      ARRAY['Norge', 'Sverige', 'EU']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Caretech',
      'Norsk leverandør og formidler av spesialiserte hjelpemidler for personer med funksjonsnedsettelser — rullestoler, stå- og gåtreningsutstyr (Innowalk), liggetraller, personløftere og hygieneutstyr. Caretec samarbeider med importører over hele landet og er spesielt aktiv i Nord-Norge. Utstyret kan bidra til tryggere og mer selvstendig hverdag hjemme for personer med nedsatt funksjonsevne, ofte tildeles via NAV Hjelpemiddelsentral etter ergoterapeutisk kartlegging.',
      'Trygghet i hjemmet',
      ARRAY['hjelpemiddel', 'rullestol', 'mobilitet', 'funksjonsnedsettelse']::text[],
      'https://www.caretec.no/',
      NULL,
      'Caretec AS',
      ARRAY['Norge']::text[],
      'Eksempel på hjelpemiddel-leverandør snarere enn velferdsteknologi-plattform — relevant for å vise bredden i teknologilandskapet rundt hjemmeboende med funksjonsnedsettelse.',
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Ably Medical',
      'Norsk helsesatsning (stiftet 2016, Ålesund) som utvikler berøringsfri sensorteknologi for pasientovervåking. Hovedproduktet LYNG er en sensormatte plassert under madrassen som overvåker tilstedeværelse, bevegelse og sengeutgang — med indikative trender for puls og respirasjon. Varsler pleiere når en beboer forlater sengen eller forblir immobil for lenge. Utviklet for sykehjem og hjemmesykepleie, med støtte fra Innovasjon Norge til prosjektet «framtidas pasientrom».',
      'Trygghet i hjemmet',
      ARRAY['startup', 'sensor', 'sensormatte', 'fall', 'seng', 'berøringsfri']::text[],
      'https://ablymed.com/no/technology',
      NULL,
      'Ably Medical AS',
      ARRAY['Norge']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Dignio',
      'Norsk helseteknologiselskap som gjør helsetjenester mindre avhengige av tid og sted — med digital hjemmeoppfølging og elektroniske medisindispensere samlet i én plattform. Dignio Prevent gir helsepersonell oversikt, varsler og beslutningsstøtte, mens pasientappen MyDignio brukes til videosamtaler, skjemaer, målinger og meldinger. Medisindispenseren varsler brukeren ved dosetid og gir beskjed til helsepersonell dersom medisinen ikke tas. Brukes i over halvparten av norske kommuner og ved flere sykehus.',
      'Helse og medisiner',
      ARRAY['medisindispenser', 'digital hjemmeoppfølging', 'MyDignio', 'målinger']::text[],
      'https://dignio.com/no/',
      NULL,
      'Dignio AS',
      ARRAY['Norge']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Evondos',
      'Automatisert medisindispenser som fungerer som et låst og sikkert medisinskap — minner brukeren når det er tid for medisin, deler ut riktig dose fra multidoserull og varsler helsepersonell dersom en dose uteblir. CE-merket medisinteknisk utstyr med 99 % etterlevelse av ordinert medisinering. Kan brukes i selvstendig modus eller assistert modus med videokommunikasjon for digitalt hjemmebesøk. Brukes av hundrevis av helse- og omsorgsorganisasjoner i Norden og Europa, med kontor i Oslo.',
      'Helse og medisiner',
      ARRAY['medisindispenser', 'legemiddelsikkerhet', 'automatisert', 'video']::text[],
      'https://www.evondos.no/',
      NULL,
      'Evondos Group',
      ARRAY['Norge', 'Norden', 'Europa']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Everon Global',
      'Europas største leverandør av digitale, trådløse og skybaserte løsninger for assisert boende (assisted living). Everon-økosystemet kombinerer intelligent programvare og trådløs maskinvare for å gi helse-, omsorgs- og boligleverandører sanntidsinformasjon og «patterns of life»-data — for mer målrettet og forebyggende omsorg. Over 150 000 installasjoner og mer enn én million tilkoblinger på tvers av Finland, Sverige og Storbritannia. Åpent og skalerbart system som støtter både hjemmeboende og institusjoner.',
      'Helse og medisiner',
      ARRAY['assisted living', 'sensorer', 'sky', 'økosystem', 'trådløs']::text[],
      'https://everon.global/',
      NULL,
      'Everon Group',
      ARRAY['Finland', 'Sverige', 'Storbritannia']::text[],
      'Primært etablert i Finland, Sverige og UK — relevant som eksempel på internasjonalt assisted living-økosystem, snarere enn en etablert norsk leverandør.',
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Pilloxa',
      'Svensk digital helseplattform for oppfølging av pasienter — med særlig fokus på medisinering og etterlevelse av behandling. Helseaktører kan sette opp merkevarede app-programmer med påminnelser, medisininformasjon, oppgaver og opplæringsmateriale. Kan kobles til den smarte medisinesken Pilloxa One, som registrerer når doser tas eller utelates. Støtter norsk språk, og har samarbeidet med Universitetet i Oslo om klinisk validering (ASTORIA-studien) for pasienter med hjerterytmeforstyrrelser.',
      'Helse og medisiner',
      ARRAY['medisinoppfølging', 'app', 'smart pillbox', 'etterlevelse']::text[],
      'https://pilloxa.com/',
      NULL,
      'Pilloxa AB',
      ARRAY['Norge', 'Sverige', 'Norden']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'DigiRehab',
      'Digital plattform for styrketrening og rehabilitering tilpasset eldre — med kartlegging, personlige treningsprogrammer og løpende oppfølging av funksjonsevne. Tilbys som Prehab (forebygging før pleiebehov), Rehab (for hjemmeboende med pleie) og Care (sykehjem). Eldre trener typisk 20 minutter to ganger i uken hjemme sammen med helsepersonell, basert på Helsedirektoratets retningslinjer for styrketrening mot fall. Brukes i norske kommuner som Nesna, Gjerstad og Etnedal, med mål om å utsette pleiebehov og øke selvhjulpenhet.',
      'Helse og medisiner',
      ARRAY['styrketrening', 'rehabilitering', 'prehab', 'fallforebygging', 'senior']::text[],
      'https://digirehab.no/',
      NULL,
      'DigiRehab A/S',
      ARRAY['Norge', 'Danmark']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'KOMP',
      'Skjerm utviklet for eldre og personer med kognitive utfordringer som ønsker enkel kontakt med familie — uten touchskjerm, menyer eller passord. Familien styrer alt via Komp-appen: sender bilder og meldinger, starter videosamtaler som besvares automatisk etter ti sekunder, og setter enheten i hvilemodus om natten. Skjermen har én fysisk knapp (på/av og volum), stor skjerm med god kontrast, og kobles til Wi-Fi eller innebygd 4G. Brukes av over 11 000 eldre og mer enn 130 norske kommuner.',
      'Kontakt og kommunikasjon',
      ARRAY['skjerm', 'video', 'bilder', 'familie', 'enkel teknologi']::text[],
      'https://komp.family/',
      NULL,
      'No Isolation (Komp)',
      ARRAY['Norge']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Nattugla',
      'Intelligent kamerasensor med innebygd AI for digitalt tilsyn i eldreomsorgen — oppdager automatisk hendelser som fall, at brukeren forlater sengen eller rommet, uteblitt vekking eller høy lyd, og varsler helsepersonell ved behov. Ved utløst alarm kan helsepersonell gjøre digitalt tilsyn med krystallklar toveis lyd og bilde direkte på smarttelefonen. Personvernet ivaretas med anonymisering på enheten, ende-til-ende-kryptering og ingen lagring av video i skyen. Godkjent av Norsk Helsenett og integreres med plattformer som Hepro Respons.',
      'Kontakt og kommunikasjon',
      ARRAY['AI', 'digitalt tilsyn', 'hendelsesdeteksjon', 'fall', 'video']::text[],
      'https://nattugla.no/nb/',
      NULL,
      'Nattugla AS',
      ARRAY['Norge', 'Europa']::text[],
      'Ofte plassert under trygghet/digitalt tilsyn — inkludert her også for kommunikasjonsdimensjonen mellom bruker og helsepersonell.',
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Picomed',
      'Norsk leverandør av hjelpemidler og velferdsteknologi til eldre og funksjonshemmede — med salg til kommuner, institusjoner og privatpersoner. Sortimentet omfatter omgivelseskontroll (styring av lys, dør, TV og telefon), varslingssystemer for demens, epilepsi og fall, samt produkter for demensomsorg, søvn og spisevansker. Picomed utvikler og produserer norsk assistiv teknologi fra Gjerstad, og er også distributør av produkter som robotselen Paro og vektprodukter fra Novista.',
      'Kontakt og kommunikasjon',
      ARRAY['hjelpemiddel', 'omgivelseskontroll', 'varsling', 'demens', 'distributør']::text[],
      'https://www.picomed.no/',
      NULL,
      'Picomed AS',
      ARRAY['Norge']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Paro',
      'Terapeutisk robot utformet som en selunge, utviklet i Japan for å skape glede, stimulere sosial kontakt og øke livskvaliteten hos personer med demens eller hjerneskade. Paro reagerer på berøring, tale og lys med bevegelser, lyder og øyebevegelser — og kan virke beroligende, stimulere språk og dempe uro. Distribueres i Norge av Picomed, og bruk krever sertifisering av pleiepersonell. Skal fungere som supplement til menneskelig kontakt, ikke erstatning — og er mest utbredt på demensavdelinger og i dagtilbud.',
      'Kontakt og kommunikasjon',
      ARRAY['robotsel', 'demens', 'terapi', 'sosial robot', 'omsorgsterapi']::text[],
      'https://www.picomed.no/demensomsorg/selen-paro/',
      NULL,
      'PARO Robots (distribuert av Picomed)',
      ARRAY['Norge', 'Japan', 'globalt']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Hjelpemiddelpartner',
      'Norsk leverandør av hjelpemidler som gjør hverdagen enklere og mer selvstendig for personer med nedsatt funksjonsevne. Utvalget omfatter blant annet Active Up W — et batteridrevet løftesete for rullestol som hjelper brukeren å reise og forflytte seg selv (15 cm løftehøyde) — samt Active Up for bruk i hjemmet, rullestoler og rullatorer, elektrisk tannbørste med sug (Active Oral Clean), og strømpepåtager. Mange produkter kan søkes via NAV Hjelpemiddelsentral; privatkjøp via Velferdsbutikken.no.',
      'Hverdagsmestring',
      ARRAY['hjelpemiddel', 'rullestol', 'løftesete', 'hygiene', 'mobilitet']::text[],
      'https://www.hjelpemiddelpartner.no/',
      NULL,
      'Hjelpemiddelpartner AS',
      ARRAY['Norge']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Varodd Velferdsteknologi',
      'Landsdekkende leverandør av hjelpemidler til helse-Norge siden 1963, med bredt sortiment til hjelpemiddelsentraler, kommuner, sykehjem og sykehus. Tilbyr senger, madrasser, hygienehjelpemidler, personløftere, vendesystemer, rullatorer og annet teknisk utstyr — fra Lindesnes til Honningsvåg. Målet er produkter som gir økt trygghet, livskvalitet og selvhjulpenhet i dagliglivet, og som bidrar til at flere kan bo hjemme lenger.',
      'Hverdagsmestring',
      ARRAY['hjelpemiddel', 'senger', 'madrasser', 'hygiene', 'distributør']::text[],
      'https://hjelpemidler.varodd.no/',
      NULL,
      'Varodd Velferdsteknologi AS',
      ARRAY['Norge']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Abilia',
      'Leverandør med lang erfaring innen hjelpemidler for personer med funksjonsnedsettelser — uavhengig av alder og behov. Produktene hjelper med struktur i hverdagen, kommunikasjon med omgivelsene, styring av funksjoner i hjemmet og varsling ved behov. Sortimentet omfatter kommunikasjon (Grid, talemaskiner), kognisjon og planlegging, omgivelseskontroll, varsling og vektprodukter. Mange løsninger kan søkes via NAV Hjelpemiddelsentral. Abilia overtok Picomed i 2024.',
      'Hverdagsmestring',
      ARRAY['hjelpemiddel', 'kommunikasjon', 'kognisjon', 'omgivelseskontroll', 'varsling']::text[],
      'https://www.abilia.com/nb/vare-hjelpemidler',
      NULL,
      'Abilia AB',
      ARRAY['Norge', 'Sverige', 'Norden']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Guldmann',
      'En av verdens ledende leverandører av løfteløsninger for helsevesenet — takheissystemer, mobile løftere, løfteseler og tilbehør for trygg pasienthåndtering. Brukes i hjemmeboende omsorg, sykehjem, sykehus og rehabilitering for å redusere belastning på pleiere og øke pasientsikkerheten ved forflytning. Guldmann tilbyr også prosjektrådgivning ved installasjon av skinnesystemer i nye og eksisterende bygg.',
      'Hverdagsmestring',
      ARRAY['løft', 'takheis', 'pasienthåndtering', 'ergonomi', 'forflytning']::text[],
      'https://www.guldmann.com/no/',
      NULL,
      'Guldmann AS',
      ARRAY['Norge', 'globalt']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'YetiCare',
      'Finsk helseteknologiløsning med store berøringsskjermer (Yetitablet) og skreddersydde apper for eldre og personer med kognitive eller fysiske funksjonsnedsettelser. Den store skjermen med enkelt brukergrensesnitt (YetiLauncher) inviterer til sosial interaksjon, gruppeaktiviteter, reminisensarbeid og motorisk rehabilitering — tilpasset ulike ferdighetsnivåer. Brukes på sykehjem og omsorgsinstitusjoner i Norge, blant annet ved Sandsli bo- og aktivitetssenter i Bergen. Distribueres i Norge via VilMer.',
      'Hverdagsmestring',
      ARRAY['nettbrett', 'aktivitet', 'rehabilitering', 'stor skjerm', 'eldre']::text[],
      'https://yeticare.fi/no/',
      NULL,
      'YetiCare Oy',
      ARRAY['Norge', 'Finland']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Tessa',
      'Sosial zorgrobot utformet som en liten blomsterpotte — utviklet for personer med kognitiv svikt eller demens som trenger støtte i daglige rutiner. Tessa gir verbale påminnelser og veiledning på faste tidspunkter for mat, medisin, drikke og daglige gjøremål, styrt av pårørende eller helsepersonell via app. Roboten stiller også korte spørsmål om hvordan det går, med svar direkte i appen. Målet er økt selvstendighet og mindre behov for fysisk hjelp i hverdagen.',
      'Hverdagsmestring',
      ARRAY['robot', 'demens', 'selvhjelp', 'påminnelser', 'kognitiv støtte']::text[],
      'https://www.tinybots.nl/zorgrobot-tessa/maak-kennis-met-tessa',
      NULL,
      'Tinybots (Nederland)',
      ARRAY['Nederland', 'Europa']::text[],
      'Primært etablert i Nederland — relevant som eksempel på kognitiv støtte-teknologi, sammenlignbart med struktur- og påminnelsesverktøy i norsk eldreomsorg.',
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Hemby',
      'Finsk #agetech-startup (grunnlagt 2018, omdøpt fra Helppy til Hemby i 2025) som tilbyr teknologidrevet hjemmeomsorg og hverdagsassistanse — kobler personer som trenger hjelp med lokale omsorgspersoner via app. Tjenesten gir personlig, fleksibel hjelp hjemme med faste, kjente hjelpere, og en familieportal for pårørende. Opererer i Finland, Tyskland og London. Navnet «Hemby» betyr «hjembygd» på skandinaviske språk.',
      'Hverdagsmestring',
      ARRAY['startup', 'hjemmehjelp', 'omsorg', 'app', 'pårørende']::text[],
      'https://www.hemby.com/en',
      NULL,
      'Hemby Oy (tidligere Helppy)',
      ARRAY['Finland', 'Tyskland', 'Storbritannia']::text[],
      'Ikke etablert i Norge ennå — relevant som eksempel på plattformmodell for lokal hjemmehjelp og pårørendestøtte, snarere enn tradisjonell velferdsteknologi.',
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'FARSEEING',
      'EU-finansiert forskningsprosjekt (2012–2015) som utviklet teknologier for å forebygge, detektere og håndtere fall hos eldre. SINTEF og NTNU testet blant annet en «trygghetsalarm 2.0» — et falldeteksjonsbelte med mobil og fallalgoritme — i Trondheim med eldre fra Byneset og Laugsand. Prosjektet bygde verdens største database over reelle fall registrert med bærbare sensorer, utviklet fallrisikovurderingsverktøyet FRAT-up, og forsket på rehabilitering etter fallskader.',
      'Tjenester rundt hjemmet',
      ARRAY['forskning', 'fall', 'forebygging', 'sensorer', 'rehabilitering']::text[],
      'https://www.sintef.no/en/projects/2012/farseeing/',
      NULL,
      'SINTEF / NTNU (EU-prosjekt)',
      ARRAY['Norge', 'Europa']::text[],
      'Forskningsprosjekt, ikke et kommersielt produkt — relevant som eksempel på norsk forskning som la grunnlag for senere fallteknologi og kommersialisering (f.eks. mHealth Technologies).',
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Phoniro',
      'Svensk pioner innen velferdsteknologi som tilbyr et sammenhengende økosystem med smarte, fysiske løsninger for eldreomsorg. Phoniro Care er en tjenesteplattform med moduler for digital nøkkelhåndtering (150 000 installerte e-låser), tids- og tjenesteoppfølging, trygghetsalarmer (Phoniro 6000), e-tilsyn og analyseverktøy — alt samlet i én database. Brukes i over 200 svenske kommuner og integreres i Norge med TelluCare. Målet er å frigjøre tid til menneskelig omsorg ved å automatisere administrative oppgaver.',
      'Tjenester rundt hjemmet',
      ARRAY['plattform', 'økosystem', 'e-lås', 'trygghetsalarm', 'e-tilsyn']::text[],
      'https://phoniro.com/no/om-phoniro/',
      NULL,
      'Phoniro AB',
      ARRAY['Norge', 'Sverige', 'Norden']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'AddSecure',
      'Europeisk leverandør av sikker IoT-tilkobling og ende-til-ende-løsninger for kritisk alarmkommunikasjon. Smart Care-porteføljen omfatter trygghetsalarmer, GPS-klokker, sensorer og døgnbemannet alarmsentral (ARC) med toveis tale — primært etablert i Finland (200+ kommuner). I Norge leverer AddSecure alarmoverføring, teknisk alarm og IoT-løsninger for bygg, heis og sikkerhetsinstallasjoner. Norsk opprinnelse via Safetel og Securinet (fusjon 2014).',
      'Tjenester rundt hjemmet',
      ARRAY['alarm', 'IoT', 'alarmsentral', 'trygghetsalarm', 'overføring']::text[],
      'https://www.addsecure.com/smart-care-mo-start-page/',
      NULL,
      'AddSecure Group',
      ARRAY['Norge', 'Norden', 'Europa']::text[],
      'Beslektet med Securitas Technology (alarmer og sikkerhet), men separate selskaper — AddSecure fokuserer mer på IoT-kommunikasjon og alarmoverføring, mens Securitas Technology er integrator for pasientvarsling og institusjonsløsninger.',
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      'Teton.ai',
      'Dansk helsesatsning (grunnlagt 2020) som bruker deep learning og computer vision til autonomt overvåkningssystem for sykehjem og sykehus. Takmonterte optiske sensorer registrerer aktivitet i rommet — søvn, mobilitet, stilling og fallsituasjoner — uten at beboeren bærer utstyr. All bildebehandling skjer lokalt, uten lagring av video, for å ivareta personvern. Gir helsepersonell sanntidsvarsler og langsiktige trenddata for å forebygge fall og effektivisere arbeidsflyt.',
      'Tjenester rundt hjemmet',
      ARRAY['AI', 'computer vision', 'overvåking', 'fall', 'autonom']::text[],
      'https://www.teton.ai/',
      NULL,
      'Teton AI (Danmark)',
      ARRAY['Danmark', 'Europa']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    ),
(
      '9Solutions',
      'Nordens ledende leverandør av sanntidslokalisering (RTLS) og kommunikasjonsløsninger for helse- og omsorgssektoren. Systemet bruker et trådløst Bluetooth-nettverk for romnivå-presisjon av alarmer, personell, pasienter og utstyr — integrert med pasientvarsel, personalsikkerhet og utstyrssporing i ett system. Brukes i over 2 000 helseorganisasjoner i Norden, inkludert 80 % av Finlands universitetssykehus. Tilbyr også løsninger for sykehjem og hjemmeboende omsorg.',
      'Tjenester rundt hjemmet',
      ARRAY['RTLS', 'lokalisering', 'pasientvarsel', 'sykehus', 'sykehjem']::text[],
      'https://www.9solutions.com/en/about-us/rtls',
      NULL,
      '9Solutions Oy (ASSA ABLOY)',
      ARRAY['Finland', 'Sverige', 'Norden']::text[],
      NULL,
      false,
      'f3c8e797-4fa1-44c8-868e-a674b1576c3a'::uuid
    );
